#-------------------------------
# General Site Settings
title: mas,bah! Nana
logo: '/images/logo-canal1.png' # You can add own logo. For example '/images/logo.png'.
description: # Aditu is a stylish and modern dark theme with a clean and unique design.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://masbahnana.github.io" # "https://shebangbash.dev" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Nana
  avatar: '/images/profile.jpeg'


#-------------------------------
# Hero Settings
hero:
  title: #Natalia
  description: #Thoughts, stories and ideas.
  image: '/images/capa.jpg'


#-------------------------------
# Contact Settings
contact:
  email: natr@hey.com # Add your email for contant form
  description: #The Force is strong with this one. I have you now. I find your lack of faith disturbing. Hey, Luke! May the Force be with you. She must have hidden the plans in the escape pod. Send a detachment down to retrieve them, and see to it personally, Commander. There’ll be no one to stop us this time! # Add a description of your form

# NOTE
# Aditu theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/masbahnana"}
- {icon: "ion-logo-octocat", link: "https://github.com/masbahnana"}
- {icon: "ion-logo-twitch", link: "https://twitch.tv/masbahnana"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/c/masbahnana"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/nanadasilva/"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/masbahnana"}
- {icon: "logo-gitlab", color: white, link: "https://gitlab.com/masbahnana"}




#-------------------------------
# Comment Section (Disqus)
layout: default
comments: true
disqus-identifier: shebangbash # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: github.us10.list-manage.com/subscribe/post?u=d9553c4c9b8b4bba4fb3d8262&amp;id=1d2ecdeb5d # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

theme: jekyll-theme-cayman
